//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemVenda
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public decimal Quantidade { get; set; }
        public int VENDAId { get; set; }
    
        public virtual VENDA VENDA { get; set; }
    }
}
